import { GoogleGenAI, Type } from "@google/genai";
import { Invoice, Customer, InvoiceItem } from '../types';

// WARNING: Hardcoding keys is not recommended for production.
// Replace this with your actual Gemini API Key.
const GEMINI_API_KEY = "YOUR_GEMINI_API_KEY";

if (!GEMINI_API_KEY || GEMINI_API_KEY === "YOUR_GEMINI_API_KEY") {
    // This is a developer-facing error, so console.error is appropriate.
    // The main app will show a more user-friendly message if the AI service fails.
    console.error("Fatal Error: Gemini API key is not configured. Please add your API key to 'services/geminiService.ts'.");
}

// Initialize the Google Gemini AI client with the hardcoded API key.
const ai = new GoogleGenAI({ apiKey: GEMINI_API_KEY });


// This represents the structure of the invoice generated by the AI
type GeneratedInvoiceCore = Omit<Invoice, 'id' | 'status' | 'customer' | 'customer_id' | 'user_id'> & {
    items: Omit<InvoiceItem, 'id'>[],
    client: Omit<Customer, 'id' | 'user_id'>
};


const INVOICE_SCHEMA = {
    type: Type.OBJECT,
    properties: {
        invoice_number: { type: Type.STRING },
        invoice_date: { type: Type.STRING },
        due_date: { type: Type.STRING },
        client: {
            type: Type.OBJECT,
            properties: {
                name: { type: Type.STRING },
                address: { type: Type.STRING },
                phone: { type: Type.STRING },
                gstin: { type: Type.STRING, description: "Client's GST Identification Number. Can be an empty string if not provided." },
            },
            required: ["name", "address", "phone", "gstin"],
        },
        items: {
            type: Type.ARRAY,
            items: {
                type: Type.OBJECT,
                properties: {
                    name: { type: Type.STRING },
                    unit_price: { type: Type.NUMBER },
                    quantity: { type: Type.NUMBER },
                    line_total: { type: Type.NUMBER },
                },
                required: ["name", "unit_price", "quantity", "line_total"],
            },
        },
        subtotal: { type: Type.NUMBER },
        gst_percent: { type: Type.NUMBER, description: "The Goods and Services Tax (GST) percentage." },
        gst_amount: { type: Type.NUMBER, description: "The calculated GST amount." },
        total_amount: { type: Type.NUMBER },
        notes: { type: Type.STRING },
    },
    required: [
        "invoice_number", "invoice_date", "due_date", "client", "items",
        "subtotal", "gst_percent", "gst_amount", "total_amount", "notes"
    ]
};

const buildPrompt = (
    customer: Customer, 
    invoice_number: string, 
    invoice_date: string, 
    due_date: string,
    items: {name: string, unit_price: number|string, quantity: number|string}[],
    gst_percent: number|string,
    notes: string
    ): string => {
    
  const itemsList = items.map(item =>
    `${item.name}, ${item.unit_price}, ${item.quantity}`
  ).join('\n');

  return `
You are an Invoice Generation AI for businesses in India. Your task is to generate a clean and accurate invoice in structured JSON format. The currency is Indian Rupees (INR).

### INPUT:
Client Name: ${customer.name}
Client Address: ${customer.address}
Client Phone: ${customer.phone}
Client GSTIN: ${customer.gstin}
Invoice Number: ${invoice_number}
Invoice Date: ${invoice_date}
Due Date: ${due_date}
Items List (Name, Unit Price, Quantity):
${itemsList}
GST Percentage: ${gst_percent}
Additional Notes: ${notes}

### RULES:
1. All monetary values should be treated as INR.
2. Calculate line_total for each item (unit_price * quantity).
3. Calculate subtotal (sum of all line_total values).
4. Calculate gst_amount ((subtotal * gst_percent) / 100).
5. Calculate total_amount (subtotal + gst_amount).
6. Output must be JSON only. The client object must contain "phone" and "gstin" keys.
`;
};

export const generateInvoiceJson = async (
    customer: Customer, 
    invoice_number: string, 
    invoice_date: string, 
    due_date: string,
    items: {name: string, unit_price: number|string, quantity: number|string}[],
    gst_percent: number|string,
    notes: string
): Promise<Omit<Invoice, 'id' | 'status' | 'user_id'>> => {

  if (!GEMINI_API_KEY || GEMINI_API_KEY === "YOUR_GEMINI_API_KEY") {
    throw new Error("Gemini API key is not configured.");
  }

  const prompt = buildPrompt(customer, invoice_number, invoice_date, due_date, items, gst_percent, notes);

  try {
    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash',
        contents: prompt,
        config: {
            responseMimeType: 'application/json',
            responseSchema: INVOICE_SCHEMA,
        },
    });

    const text = response.text.trim();
    const parsed: GeneratedInvoiceCore = JSON.parse(text);
    
    // Destructure the AI's 'client' object and discard it.
    const { client, ...invoiceCore } = parsed;

    // Combine the cleaned AI data with the full customer object and customer_id
    // to create a complete object that matches our app's data structure.
    return { 
        ...invoiceCore, 
        customer: customer, 
        customer_id: customer.id 
    };

  } catch (error) {
    console.error("Error generating invoice with Gemini:", error);
    throw new Error("Failed to generate invoice from AI. Please check the input data and try again.");
  }
};